### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by XVilka** [nitram2342/degate#22]
Since there were many improvements since the last one it make sense to carve a new one.

**Comment by XVilka** [comment]
https://github.com/nitram2342/degate/commit/488e6d35a33bfc8d30a3120553724d79f76ccb5e is this one?

**Comment by nitram2342** [comment]
From time to time, I tag a new release, but honestly I am a bit lazy on that.

**Comment by XVilka** [comment]
@nitram2342 hmm, but they are not shown here then: https://github.com/nitram2342/degate/releases
